export type Account={id:string;name:string;openingBalance:number;bankNumber?:string;balance?:number};
export type Tx={id:string;accountId:string;amount:number;date:string;category:string;note:string;source:string;transferId?:string|null;createdAt?:string};
export type Budget={id:string;month:string;category:string;amount:number};
export type Data={accounts:Account[];transactions:Tx[];budgets:Budget[];bank?:{configured:boolean;linkedAccounts:number;lastReceived:string|null}};
export const categories=['food','transport','shopping','bills','health','entertainment','salary','other','transfer'];
export const icons:Record<string,string>={food:'↗',transport:'↗',shopping:'↗',bills:'↗',health:'↗',entertainment:'↗',salary:'↙',other:'↗',transfer:'⇄'};
export const palette=['#6934D2','#F0A55B','#71ADA2','#889BE0','#CE7F9D','#85966B','#446B55','#A7A2B3'];
export function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function demo():Data {const m=localDate().slice(0,7);return {accounts:[{id:'cash',name:'Cash',openingBalance:1500000},{id:'bank',name:'Everyday account',openingBalance:12500000}],transactions:[{id:'d1',accountId:'bank',amount:28000000,date:`${m}-01`,category:'salary',note:'Monthly salary',source:'manual'},{id:'d2',accountId:'bank',amount:-1250000,date:`${m}-03`,category:'shopping',note:'Everyday essentials',source:'manual'},{id:'d3',accountId:'cash',amount:-85000,date:`${m}-05`,category:'food',note:'Coffee & lunch',source:'manual'},{id:'d4',accountId:'bank',amount:-780000,date:`${m}-06`,category:'bills',note:'Internet & electricity',source:'manual'},{id:'d5',accountId:'cash',amount:-120000,date:`${m}-07`,category:'transport',note:'Weekend ride',source:'manual'}],budgets:[{id:'b1',month:m,category:'food',amount:3000000},{id:'b2',month:m,category:'shopping',amount:2000000}]};}
export function summary(rows:Tx[]){const expense=rows.filter(t=>!t.transferId&&t.category!=='transfer'&&t.amount<0).reduce((s,t)=>s-t.amount,0),income=rows.filter(t=>!t.transferId&&t.category!=='transfer'&&t.amount>0).reduce((s,t)=>s+t.amount,0);return {expense,income};}
